### ISSUE TITLE
drysegs - plot design

### ISSUE THREAD

**Issue by rhull21** [rhull21/re_app#29]
* ~~turn animation off by default~~
* ~~delineate reaches by thicker horizontal lines (or a different set of colors) ~~
* ~~Landmark horizontal lines are a little cluttered. Remove? See also #28~~ 
     * ~~Select a few significant ones (e.g. reaches, Peralta Wasteway, etc).~~ 
     * ~~Make it easier to turn off~~
* ~~Vertical grid lines could help - like thicker lines 1st of the month and thinner on 15th~~
* ~~Please pivot the RM on the Y axis, so they are listed in descending order~~
* ~~Expand the plot Y axis to include the Angostura Reach, which experienced dryness for the first time in 2022~~

Updated 03162023: 
* ~~color the color flood with flow~~
* ~~hover label the features~~
* ~~x label located on top of plot~~
* ~~select bar on top of plot (on going)~~ 
* note river miles as markers relative to a zero point

**Comment by rhull21** [comment]
@agropunk lmk if you want to meet to discuss how to divvy these up on plotly

**Comment by rhull21** [comment]
Great reference for plotly API 
- https://plotly.com/python-api-reference/ 

Possible way to turn off animation 
- https://community.plotly.com/t/autoplay-of-animations-in-plotly-graph-objects/36420

**Comment by rhull21** [comment]
Chad comments 03212023: 
* Description notes: Provide navigational guidance, explain double-click to zoom out
     * @agropunk 
* Functional optimizations: 
     
     * ~~incorporate a download xls button (pushes the xls version of all years of data).~~
         * _done_
     * Is it possible to show all?
     * Include at least April 1 through November 15 for each year. 
          * @qi-ball this and the above going to increase load times and slow things down; additionally, stuff is all indexed for June - October. I'd estimate a couple hours to make the updated. Are we sure?

**Comment by rhull21** [comment]
most of these issues addressed in commit 70218865, moving over to discussion

**Comment by qi-ball** [comment]
Yes, its important to include data beginning April 1 because we've had drying beginning that month during extreme years like 2018, which are critically important while evaluating drying info alongside other variables like silvery minnow population size. Showing only a portion of each year would be misleading.

**Comment by rhull21** [comment]
Plots adjusted to include data beginning April 1 through November 30
