### ISSUE TITLE
Delineating subreaches

### ISSUE THREAD

**Issue by rhull21** [rhull21/re_app#39]
@qi-ball Is it a priority to delineate between subreaches like the Abeytas and Peralta? If so, could you please send upstream and downstream extents for the subreaches as the table exists but is currently empty. 

Thank you!

Q

**Comment by qi-ball** [comment]
Reach | SubReach | Upstream_RM | Downstream_RM

Angostura | Albuquerque | 194 | 172
Isleta | Peralta | 169 | 145
Isleta | Abeytas | 140 | 120
San Acacia | Socorro | 114 | 63
San Acacia | Below Ft Craig | 63 | 59
San Acacia | Above LFCC Terminus | 58 | 54



</body>

</html>

**Comment by rhull21** [comment]
@rhull21 add subreaches
