### ISSUE TITLE
reach filtering criteria

### ISSUE THREAD

**Issue by rhull21** [rhull21/re_app#53]
For the database to consider a stretch of `dry length` to be 'within reach', the *entire* segment in question must be in reach. SQL below: 

        ```
        	((
        			`dry_length`.`rm_up` >= (
        			SELECT
        			`downreachcalc` ( 'Isleta' ))) 
        		AND (
        			`dry_length`.`rm_up` <= (
        			SELECT
        			`upreachcalc` ( 'Isleta' )))) 
          ```
  
This excludes any dry lengths that cut across any two reaches, meaning they don't get counted in the various views that count dryness by reach (i.e. `dry/drylen` and `dry/drycomp` in the website). I'm not sure how many of these edge cases there are, but an alternative is to use `OR` criteria, meaning any dry length that is at least partially in a given reach  would get selected. This would have the impact of also meaning those drylengths are double counted. 

Any thoughts about this tradeoff? Maybe I'm over thinking it

**Comment by qi-ball** [comment]
At this stage there are not any instances where dry segments fall along the edges of any ot the reaches. They neatly fall within a reach
